name: flutter_base
description: "A new Flutter project."
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dartz: ^0.10.1
  dio: ^5.9.0
  retrofit: 4.7.3
  json_annotation: 4.9.0
  get_it: ^8.2.0
  shared_preferences: ^2.5.3
  flutter_dotenv: ^6.0.0
  go_router: ^16.2.1
  crypto: ^3.0.6
  flutter_svg: ^2.2.1
  lottie: ^3.3.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  octo_image: ^2.1.0
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0

  build_runner: 2.5.4
  flutter_gen_runner: 5.12.0
  json_serializable: 6.9.5
  retrofit_generator: 9.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/raw/
    - env/

  fonts:
    - family: Pretendard
      fonts:
        # 400
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
          style: normal
        # 500
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
          style: normal
        # 600
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
          style: normal
        # 700
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
          style: normal
        # 800
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
          style: normal
        # 900
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
          style: normal

flutter_gen:
  output: lib/resources/generated/
  integrations:
    flutter_svg: true
    lottie: true

  colors:
    inputs:
      - assets/colors/colors.xml

import_sorter:
  ignored_files:
    - lib/resources/generated/
